kind: ScheduledJob
apiVersion: batch/v2alpha1
metadata:
  name: updatestats
  namespace: dewikigreetbot
spec:
  schedule: "15 21 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: updatestats
            image: docker-registry.tools.wmflabs.org/toollabs-python35-base:latest
            workingDir: /data/project/dewikigreetbot
            command: [ "/data/project/dewikigreetbot/update-stats.sh" ]
            env:
              - name: HOME
                value: /data/project/dewikigreetbot
            volumeMounts:
              - name: home
                mountPath: /data/project/dewikigreetbot/
              - name: home
                mountPath: /mnt/nfs/labstore-secondary-tools-project/dewikigreetbot/
              - name: pywikibot-core
                mountPath: /data/project/shared/pywikibot/core
          restartPolicy: Never
          volumes:
            - name: home
              hostPath:
                path: /data/project/dewikigreetbot/
            - name: pywikibot-core
              hostPath:
                path: /data/project/shared/pywikibot/core
